### ISSUE TITLE
Scrolling and tweens really jittery in firefox

### ISSUE THREAD

**Issue by tokyobarbs** [janpaepke/ScrollMagic#316]
Hi,

As of bug #164 I have 2.0.5 version of scrollMagic and my scrolling is still super jittery in Firefox.

Does the latest code have the firefox fix you spoke of in #164?

Thanks,
Craig

**Comment by mydudechris** [comment]
I too am experiencing some pretty heavy jitter in both FF and Safari.

http://christate.is/designing/prot_scrollmagic/

I've tried a number of things from removing the debug, setting fixed heights on my sections, etc. If you scroll really slowly then it kinda works but if you scroll at a "normal" speed you'll notice a solid jump on the currently pinned slide as the new slide enters.

**Comment by mydudechris** [comment]
FWIW I've also tried removing all child elements within the pinned sections including those with separately animations—effect is still the same #255

**Comment by janpaepke** [comment]
Hi.
Jitters for Firefox should be resolved in 2.0.5.
If you experience any, chances are they are related to something else (for example tweening `top` or `left` values instead of transforms.

@tokyobarbs without a link to a jsfiddle or other demo it's impossible to help you here.
@mydudechris I can't see any jitter, which might be due to a good CPU. Make sure to disable "out-of-viewport" animations. Firefox isn't very good at optimizing those.
For example: Disable the video, once the scene is out of view. Or the loop animation of the browser image....
Also please make sure this demo stays available for future reference.

**Comment by mydudechris** [comment]
Awesome, thanks @janpaepke

**Comment by frux** [comment]
@tokyobarbs i've tired of jitters too. So I wrote plugin [Scrollissimo](https://github.com/Promo/scrollissimo) which let you specify max "step" of animation. It can make your scroll-controlled animation smoother. Check it out. I will be glad if it help you.

**Comment by pa-w** [comment]
I am still experiencing jitters for Firefox but they happened only if "Smooth Scrolling" is enabled in Preferences > Advanced or using the mouse wheel to scroll.. 

Test: http://uno.paw.mx/test.html

**Comment by daniloformagio** [comment]
Hi, I'm using the ScrollMagic v2.0.5 and experiencing jitters/jumping on Firefox and IE during mouse wheel event, the same issue as #164. 

On Chrome it's scrolling smoothly during the pin.
Dragging the scrollbar up/down or using keyboard to scroll up/down we can't reproduce the issue, it occurs only on mouse wheel event.

You can see the issue here: http://jsfiddle.net/0g7x35wm/4/

**Comment by janpaepke** [comment]
Sorry for the very long silence on this.

Firefox jitter was a persistent v2 issue caused by the timing mismatch between Firefox's scroll events and v2's rAF-based position updates. Firefox dispatches scroll events at different points in the frame lifecycle than Chrome, and v2's JS-driven repositioning of pinned elements couldn't keep up, causing visible jitter.

v3 does not reposition elements via JavaScript during scroll. It uses IntersectionObserver and ResizeObserver for detection, so there's no per-frame DOM manipulation to cause jitter in any browser.

---
**ScrollMagic v3 is now available** -- a complete rewrite with an entirely new architecture and API. v2 will not receive further updates (2.0.9 is the final release).

👉 `npm install scrollmagic@next` -- [Docs](https://github.com/janpaepke/ScrollMagic/blob/main/README.md) · [Release notes](https://github.com/janpaepke/ScrollMagic/releases/tag/v3.0.0-beta.0) · [npm](https://www.npmjs.com/package/scrollmagic/v/3.0.0-beta.0)
